### ISSUE TITLE
TW schemas?

### ISSUE THREAD

**Issue by ashleney** [MooncellWiki/OpenArknightsFBS#10]
Is there going to also be a TW branch?

edit: I did what was recommended and made my own FBS repository: https://github.com/ArknightsAssets/ArknightsFlatbuffers

**Comment by ashleney** [comment]
understandable

**Comment by Kengxxiao** [comment]
> understandable

OpenArknightsFBS is mainly a sub module of Ptilopsis Bot (an unpacking tool used in PRTS wiki), which does not use data in Longcheng server, so there are no plans to update related FBS (the tool we currently use require some necessary work on game client to parse FBS).
Game clients with lower versions than CN use FBS from an equally lower version of CN client (although typically, because YoStar has modified something in gacha_table), you can try using a lower version of FBS to build your own game data unpacker.
