### ISSUE TITLE
feat: Rollback to the original key2value structure

### ISSUE THREAD

**Issue by 050644zf** [MooncellWiki/OpenArknightsFBS#6]
Originally, the key2value structure is presented as:
```js
{key:value}
```

The new json decoded from fbs now present key2value structure as:
```js
{
"key":key_name,
"value":value
}
```

which is inconsistence with other non-CN server. For developers developing project across multiple servers, this structure change is unnecessary. 

If it's not viable to convert them during fb conversion, I think it would be a good idea to add a post-processing script to perform the conversion above.

**Comment by StarHeartHunt** [comment]
IMO Not a good idea. 

Reasons:
1. Other servers will use the same data format in future.
2. Adding a post processing script also brings uncertainty when a new release of gamedata comes. We can't know the structure before the new gamedata release, extra processing steps increase the possibility we can't get new gamedata in time and need to constantly update the script to keep up with gamedata changes.
3. Due to previous dynamic hashmap structure, HG also wrote/generated a lot code to implement this, maybe they will eventually turn to strict structure too.

**Comment by yesod30** [comment]
An option could be to add the `(key)` identifier to the dictionaries key fields, so the developers themself could auto generate the code needed to read the structure from the fsb file directly. JSON wise, the identifiers has no effect.

**Comment by StarHeartHunt** [comment]
seems can be done by modifying flatc source code. need further investigation
